springdoc:
  swagger-ui:
    path: /swagger-ui/index.html


aws:
  access_key_id: AKIA6GWZQEV6FWGMZJGF
  secret_access_key:
  s3:
    bucket: arolaz
    region: ap-southeast-1

security:
  jwt:
    token:
      secret-key: 
      expiration: 60000000

spring:
  data:
    mongodb:
      uri: mongodb+srv://rayst:nostradamus753@pizzaapp.bnsvb.mongodb.net/<dbname>?retryWrites=true&w=majority
      database: PizzaDB

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 730125817708953
            client-secret:
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthorizationScheme: form
          scope:
            - email
            - public_profile
          resource:
            userInfoUri: https://graph.facebook.com/me

        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect


logging:
  level:
    org:
      springframework:
        web: DEBUG




